# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Wing Fighter
subtitle: Best space shooting game on Mobile
email:
description: "Wing Fighter Wiki: Fighters, Commanders, Challenges, Events and more about Wing Fighter mobile game"
keywords:           WingFighter Fighter Commanders Weapon Armor Events
language:           "en" 
url:                "https://wing-fighter.github.io"
logo: "/images/WingFighter_Wiki_Logo.png"
####google_ad_client:   "ca-pub-3093097053913638"
# theme: minimal-mistakes-jekyll
# minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

minimal_mistakes_skin: default
search: true
search_provider: google
google:
  search_engine_id     :  "96084cf46afdb4605"
  instant_search       : true  

# eraofchaos/eraofchaos.github.io
repository: "wing-fighter/wing-fighter.github.io"
####comments:
####  provider  : staticman_v2
####  staticman:
####    branch    : "main"
####    endpoint  : https://eraofchaosbot.herokuapp.com/v2/entry/


#       endpoint  : https://eraofchaosbot.herokuapp.com/v3/entry/github/
#   https://eraofchaosbot.herokuapp.com/v2/connect/eraofchaosbot/eraofchaos.github.io
#     endpoint  : https://api.staticman.net/v2/entry/
#    endpoint  : https://eraofchaos.herokuapp.com/v2/entry/
#   endpoint  : https://api.staticman.net/v3/entry/github/
#   endpoint  : https://eraofchaos.herokuapp.com/v3/entry/github/  check issue with require oauthToken or token, see https://yasoob.me/posts/running_staticman_on_static_hugo_blog_with_nested_comments/


# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
  - fighter

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
#  - jemoji


#    - label: "Twitter"
#      icon: "fab fa-fw fa-twitter-square"
#      url: "https://twitter.com/"
#    - label: "GitHub"
#      icon: "fab fa-fw fa-github"
#      url: "https://github.com/"

# Analytics
analytics:
  provider               :  "google-gtag"           # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :  "G-92LWD7D281"

author:
  name   : "PilotX"
  avatar : "/images/bio-photo.jpg"
  bio    : "Camel is Horse designed by committee"
  links:
    - label: "Wing Fighter"
      icon: "fas fa-fw fa-link"
      url: "https://wing-fighter.github.io/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/WingFighterOfficial/"
    - label: "Official Discord"
      icon: "fab fa-fw fa-discord"
      url: "https://discord.gg/A3g5QpQj"
    - label: "Instagram"
      icon: "fab fa-instagram"
      url: "https://www.instagram.com/wingfighterofficial/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/WingFighter_"

footer:
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/WingFighterOfficial/"
    - label: "Official Discord"
      icon: "fab fa-fw fa-discord"
      url: "https://discord.gg/A3g5QpQj"
    - label: "Instagram"
      icon: "fab fa-instagram"
      url: "https://www.instagram.com/wingfighterofficial/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/WingFighter_"
    - label: "Reddit"
      icon: "fab fa-fw fa-reddit"
      url: "https://www.reddit.com/r/Wing_Fighter_Game/"

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/

defaults:
  # heroes
  - scope:
      path: "fighter"
      type: pages
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: true
      share: true
      sidebar:
        nav: "docs"
  - scope:
      path: "commander"
      type: pages
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: true
      share: true
      sidebar:
        nav: "docs"
  - scope:
      path: "equipment"
      type: pages
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: true
      share: true
      sidebar:
        nav: "docs"
  - scope:
      path: "gem"
      type: pages
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: true
      share: true
      sidebar:
        nav: "docs"
  - scope:
      path: "shop"
      type: pages
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: true
      share: true
      sidebar:
        nav: "docs"
  - scope:
      path: "talent"
      type: pages
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: true
      share: true
      sidebar:
        nav: "docs"
  - scope:
      path: "battle"
      type: pages
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: true
      share: true
      sidebar:
        nav: "docs"
  - scope:
      path: "item"
      type: pages
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: true
      share: true
      sidebar:
        nav: "docs"
  - scope:
      path: "pilots"
      type: pages
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: true
      share: true
      sidebar:
        nav: "docs"
  - scope:
      path: "legion"
      type: pages
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: true
      share: true
      sidebar:
        nav: "docs"
  # _docs
  - scope:
      path: "CollectionCenter"
      type: pages
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: true
      share: true
      sidebar:
        nav: "docs"
  - scope:
      path: "Planet_Wars"
      type: pages
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: true
      share: true
      sidebar:
        nav: "docs"
  - scope:
      path: "Legion_Hunt"
      type: pages
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: true
      share: true
      sidebar:
        nav: "docs"
  - scope:
      path: "it"
      type: pages
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: true
      share: true
      sidebar:
        nav: "docs"
  - scope:
      path: "fr"
      type: pages
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: true
      share: true
      sidebar:
        nav: "docs"
  - scope:
      path: "de"
      type: pages
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: true
      share: true
      sidebar:
        nav: "docs"
  - scope:
      path: "cn"
      type: pages
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: true
      share: true
      sidebar:
        nav: "docs"
  - scope:
      path: "ru"
      type: pages
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: true
      share: true
      sidebar:
        nav: "docs"
  - scope:
      path: "es"
      type: pages
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: true
      share: true
      sidebar:
        nav: "docs"
  - scope:
      path: ""
      type: docs
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      sidebar:
        nav: "docs"
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false


#category_archive:
#  type: liquid
#  path: /categories/
#tag_archive:
#  type: liquid
#  path: /tags/